### ISSUE TITLE
Game fails to end 

### ISSUE THREAD

**Issue by eeyrjmr** [ValveSoftware/Dota-Underlords#10]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/eeyrjmr/446c791fdd0e0860cbcb3102dbd01373): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Start game with medium bots
2. Win
3. Game waits for next round to start but no bots available
![2019-06-20-100804_1920x1080_scrot](https://user-images.githubusercontent.com/4564448/59836976-5c78f180-9344-11e9-97f9-7ed8f7bc2101.png)

**Comment by orcololo** [comment]
Same here. :(

**Comment by gdrewb-valve** [comment]
This is happening on all platforms and the larger team will handle it.

**Comment by gdrewb-valve** [comment]
The larger team says that one cause of this has been fixed but they're not sure if it's completely fixed.  If you're still experiencing this with a current (from early July) update please comment again.
