### ISSUE TITLE
Crash game with system after 5-10 minutes 

### ISSUE THREAD

**Issue by WithMistake** [ValveSoftware/Dota-Underlords#13]
elementary OS 5.0 Juno (64 bit)
 Kernel Name:  Linux
 Kernel Version:  4.15.0-52-generic

2. Check updates: Yes
3.  Video drive: Yes, last
4. Verifed game files: Yes

I don't know what problem, but after 5-10 minutes game and system crash. I can't do anathyning and I must reboot system. I can't check log. Is it problem game or is it problem with my driver?

**Comment by kisak-valve** [comment]
Hello @Vendetta131, what video card / driver version are you using? If possible, please check if you can ssh into the system and if you can, check `dmesg` for any relevant info.

**Comment by WithMistake** [comment]
description: VGA compatible controller
       product: Haswell-ULT Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 0b
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:44 memory:f0000000-f03fffff memory:e0000000-efffffff ioport:3000(size=64) memory:c0000-dffff

I can't ssh into the system. 

Vulkan Instance Version: 1.1.70


I think maybe i have problem with driver. When i have Dota-2 vulkan driver work fine, but after reinstall system, i can't play Dota 2 with vulkan api, because doesn't start.

**Comment by WithMistake** [comment]
I reinstall vulkan driver and now work fine. Sorry for the trouble.
