### ISSUE TITLE
Dota Underlords: Failed to Initialize Vulkan

### ISSUE THREAD

**Issue by 010110101001** [ValveSoftware/Dota-Underlords#14]
#### Your system information

* System information from steam:  https://pastebin.com/5c5hgnXM
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? I think so I just installed Ubuntu
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

I'm trying to play Dota Underlords here on my Ubuntu (previously tried ElementaryOS still not working) but when I click play the error message "Failed to Initialize Vulkan" always pops out. I have installed anything related to vulkan drivers in every site i went. Then I saw this thread in github about the topic (https://github.com/ValveSoftware/Dota-Underlords/issues/1) I tried running steam in the command line with the "-vulkan_disable_steam_shader_cache" command.

https://pastebin.com/fY9UWFRV

This is the log result when I'm trying to launch dota underlords. Hopefully, you can help me. Thank you.

**Comment by kisak-valve** [comment]
Hello @010110101001, Intel Ironlake (Gen 5 graphics) does not support Vulkan, The oldest generation of Intel chipset that can run this game is Ivybridge (Gen 7 graphics).

There's no way around this for you without newer hardware.

**Comment by 010110101001** [comment]
Oh, I tried installing Windows here on my laptop and the game works...

**Comment by 010110101001** [comment]
> Hello @010110101001, Intel Ironlake (Gen 4 graphics) does not support Vulkan, The oldest generation of Intel chipset that can run this game is Ivybridge (Gen 7 graphics).
> 
> There's no way around this for you without newer hardware.

Oh, I tried installing Windows here on my laptop and the game works... Does that mean it dont need Vulkan in Windows?

**Comment by Yetoo1** [comment]
I am having this issue on Fedora 30.

System info: https://web.archive.org/web/20191114204525/https://pastebin.com/09kEMVuT
Have you checked for system updates?: Yes
Are you using the latest stable video driver available for your system?: Yes
Have you verified the game files?: Yes

steam -vulkan_disable_steam_shader_cache doesn't work.

**Comment by kisak-valve** [comment]
Hello @Yetoo1, your issue is unrelated to the issue which was tracked here. Please open a new issue report. Also, please verify the `mesa-vulkan-drivers` package is installed on your system.
