### ISSUE TITLE
Missing models in encyclopedia/bench/shop

### ISSUE THREAD

**Issue by skeet70** [ValveSoftware/Dota-Underlords#16]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/skeet70/caa3f7db9a0d724c0bdaebb46ba6736e
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Invisible hero models in the shop and on the bench. They work fine on the board, and they flash quickly in the encyclopedia before disappearing.
![underlords invisible models half](https://user-images.githubusercontent.com/1424117/60471469-0ba9a880-9c22-11e9-8ad6-9c2bcc927072.png)

#### Steps for reproducing this issue:

1. Arch Linux, fully updated with `pacman -Syu`, nvidia drivers
2. `flatpak` installation of Steam
3. install and start Underlords. Open the encyclopedia and click a unit, or start a game and open the shop/observe the bench after buying a unit.

Seems like this is also an issue for [some Mac users](https://www.reddit.com/r/underlords/search/?q=invisible%20bench&restrict_sr=1).

**Comment by Pobega** [comment]
Looks like the same issue I saw: https://github.com/ValveSoftware/Dota-Underlords/issues/4

Are you running the game at a non-native resolution?

**Comment by skeet70** [comment]
I've tried it at pretty much every resolution, including native.

**Comment by skeet70** [comment]
This issue is still present (and the same) on the most recent versions of everything as of today.

**Comment by skeet70** [comment]
Appears to be fixed in the Big Update with the most recent everything + flatpak Steam on Arch.
