### ISSUE TITLE
Ranged creep wrong stats: Attack rate and DPS

### ISSUE THREAD

**Issue by pixelr0** [ValveSoftware/Dota-Underlords#18]
Ranged creep wrong stats: Attack rate and DPS (see attached image)
Atack rate is LOC_Number_InfinitySho and DPS -2,147,483,684

OS: Ubuntu Linux

![error](https://user-images.githubusercontent.com/333589/60727429-8afeeb00-9f46-11e9-95a5-d85a7cf0e0d4.png)

**Comment by gdrewb-valve** [comment]
This is happening on all platforms and the larger team will handle it.
