### ISSUE TITLE
Spectate and Main Menu buttons aren't visible until relaunch

### ISSUE THREAD

**Issue by theLastOfCats** [ValveSoftware/Dota-Underlords#2]
#### Your system information

* System information: Windows 10 1903
* Have you checked for system updates?: Yes 
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Spectate and Main Menu button aren't visible until relaunch and reconnect

#### Steps for reproducing this issue:

1. Lose a game
2. Get finish screen
3. Buttons aren't there 
4. Force close, relaunch and reconnect
5. Spectate and Main Menu buttons are visible now

**Comment by gdrewb-valve** [comment]
This issue tracker is only for Linux/Mac issues, but I believe this has already been fixed.
