### ISSUE TITLE
rare crash in panorama

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/Dota-Underlords#20]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
[sysinfo.txt](https://github.com/ValveSoftware/Dota-Underlords/files/3365996/sysinfo.txt)
* Have you checked for system updates?: Up to date Archlinux
* Are you using the latest stable video driver available for your system? Mesa git on Vega 64, but seems unrelated to graphics
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

It happened after quite a while of gameplay vs bots, during completey normal gameplay around the start of a round.

Unfortunately not much info from the stacktrace:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7f4094bbe780 (LWP 7279))]
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007f4069ad2fd7 in ?? () from /home/chris/oldhome/games/SteamLibraryLinux/SteamApps/common/Underlords/game/dac/bin/linuxsteamrt64/libclient.so
#2  0x000055fa6ca1ce10 in ?? ()
#3  0x000000000000eb80 in ?? ()
#4  0x00007ffce925eee0 in ?? ()
#5  0x00007f4067aa590d in ?? () from /home/chris/oldhome/games/SteamLibraryLinux/SteamApps/common/Underlords/game/bin/linuxsteamrt64/libpanorama_nov8.so
#6  0x0000000000000000 in ?? ()
```

**Comment by gdrewb-valve** [comment]
This is happening on all platforms and the larger team will handle it.
