### ISSUE TITLE
Crash unless -vulkan_disable_steam_shader_cache

### ISSUE THREAD

**Issue by fartyg** [ValveSoftware/Dota-Underlords#21]
Hello,

* System information and console.log:
 https://gist.github.com/fartyg/f208ba5aeb4183395f259064b7208769
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

Dota Underlords have previously been working perfectly without any custom launch options.
Have not played in a few days and have during that time updated both Manjaro to the latest stable update which included new Mesa driver, and Underlords to latest patch.

Unless I use -vulkan_disable_steam_shader_cache in my launch options the game crashes a few seconds in.

I have tried reinstalling the game without success. Any ideas on what I can do?

#### Steps for reproducing this issue:

1. Start game without -vulkan_disable_steam_shader_cache
2. Crash after 5-10 sec (looks like this just before: https://imgur.com/2ZRnWRe.png)

Kind regards

**Comment by kisak-valve** [comment]
Hello @fartyg, this issue is already being tracked at #19. Closing as a duplicate.
