### ISSUE TITLE
Matchmaking Status pop-up missing icon

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/Dota-Underlords#24]
#### Your system information

Archlinux

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/ec8e6d1796671c70541dae21863ed40aa2106eca/gistfile1.txt
* Have you checked for system updates?: yes
* Are you using the latest stable video driver available for your system? yes
* Have you verified the game files?: yes

#### Please describe your issue in as much detail as possible:
![2019-07-13_10-51](https://user-images.githubusercontent.com/425930/61185603-94f4ae00-a618-11e9-941b-f50068e90cbf.png)

The matchmaking popup is missing the underlords icon.

#### Steps for reproducing this issue:

1. Start matchmaking game

**Comment by gdrewb-valve** [comment]
This should be resolved now.
