### ISSUE TITLE
Underlords appears as invisible window, Vulkan missing requested extension errors

### ISSUE THREAD

**Issue by katyacm** [ValveSoftware/Dota-Underlords#26]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
[My System Info](https://gist.github.com/trenzafeeds/708bc3601a25667cccb1c20ca11975de)
Note: is seems that steam is unable to detect the make and model of my machine. It is an Acer Chromebook CB5-571-58HF. GalliurmOS is running on stock firmware.

* Have you checked for system updates?: [**Yes**/No]
* Are you using the latest stable video driver available for your system? [**Yes**/No]
* Have you verified the game files?: [**Yes**/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

After launching the game (From steam or the command line), nothing happens visually, but I am no longer able to interact with the windows in my current workspace, indicating that there is an invisible full-screen window overtop of them. 

Upon switching do a different workspace, then switching back, there appears to only be my desktop wallpaper visible, with my status bar and all other windows in the workspace invisible. `ps a` shows the Underlords startup script running, and killing the process directly from the terminal with `kill` is the only way to make that "invisible window" go away. 

[Here](https://gist.github.com/trenzafeeds/af6c24adb43a4b6c0bab925f0397ee1e) is the terminal output upon running and eventually killing the Underlords script. Note that the segmentation fault may have occurred after the `kill` command (I believe it did). 

[Here](https://gist.github.com/trenzafeeds/b00a5b45246b9a9927a7af381a552319) is the `console.log` file, which seems to be complaining of missing vulkan extensions. I was under the impression that I had installed all the required packages, but it seems I may have been incorrect. Hopefully that is the true issue here!

These are my installed vulkan packages:
```
λ ~/ dpkg -l | grep vulkan
ii  libvulkan1:amd64                       1.0.61.1+dfsg1-1ubuntu1~16.04.1                 amd64        Vulkan loader library
ii  libvulkan1:i386                        1.0.61.1+dfsg1-1ubuntu1~16.04.1                 i386         Vulkan loader library
ii  mesa-vulkan-drivers:amd64              18.0.5-0ubuntu0~16.04.1                         amd64        Mesa Vulkan graphics drivers
ii  vulkan-utils                           1.0.61.1+dfsg1-1ubuntu1~16.04.1                 amd64        Miscellaneous Vulkan utilities
```

Again, my fingers are crossed that these extensions simply need to be installed for everything to work, I just haven't been able to find anything online about these error messages pointing me in the right direction.

#### Steps for reproducing this issue:

1. `$ ./underlords.sh`
2. 
3.

**Comment by kisak-valve** [comment]
Hello @trenzafeeds,
```
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
vulkan/renderdevicevulkan.cpp 1745 CreateSwapChain():
The selected graphics queue does not support presenting a swapchain image.
```
This looks like the relevant bit of your logs, can you give https://askubuntu.com/questions/817226/how-to-enable-dri3-on-ubuntu-16-04 a read and see if it helps?

**Comment by kisak-valve** [comment]
Closing as this is a general system config issue preventing any Vulkan application from rendering on the system in question.
