### ISSUE TITLE
Game won't launch on Ubuntu 18.04 (Intel HD Graphics)

### ISSUE THREAD

**Issue by thomastondeur** [ValveSoftware/Dota-Underlords#3]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/lokixlqnt/5dd77ec6b938efd1654c30ca1e656a02
* Have you checked for system updates?: **Yes**
* Are you using the latest stable video driver available for your system? **Yes**
* Have you verified the game files?: **Yes**

#### Please describe your issue in as much detail as possible:

I expected the game to launch but it just kept crashing with the issue : "Failed to initialize Vulkan, please make sure your driver and GPU supports Vulkan"
I've updated my graphics driver, tried to run the game as underlords.sh (got a different error this time: Unable to load libpangoft.2-1-0.so, your game install may be corrupted or you have a system conflict.")
I've also added this PPA : "sudo add-apt-repository ppa:oibaf/graphics-drivers" for this package "xserver-xorg-video-intel" but nothing changed
-vulkan_disable_steam_shader_cache wont work aswell

#### Steps for reproducing this issue: 

1. 
2. 
3.

**Comment by builder-247** [comment]
I'm having the same issue, Linux Mint Cinnamon

**Comment by AdamSzopa** [comment]
Are you sure the i3-7020U CPU support Vulkan? I could't find any confirmation. And Vulkan is required.

**Comment by danginsburg** [comment]
I think HD 620 KBL should support Vulkan - user is on mesa 18.2.8.  Is it possible for you to try a newer version of mesa?

**Comment by thomastondeur** [comment]
Updated to mesa v19.2, didn't fix it. I still get the same errors, when I both run from Steam or from underlords.sh

**Comment by Jayman2000** [comment]
I have a laptop with Ubuntu 18.04 and Intel integrated graphics, and I had this same problem. I fixed it by doing:
1. `# apt-get install mesa-vulkan-drivers vulkan-utils`
2. Reboot
3. `$ vulkaninfo`
(this was just to make sure that my system supported Vulkan)

**Comment by thomastondeur** [comment]
Thanks a lot!!! This fixed it !
