### ISSUE TITLE
2019-08-30 Today Underlords  does not start (yesterday It was working)

### ISSUE THREAD

**Issue by colas-sebastien** [ValveSoftware/Dota-Underlords#30]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
https://gist.github.com/colas-sebastien/9db271078c21c6771bd5bb33c353a219

* Have you checked for system updates?: Yes

* Are you using the latest stable video driver available for your system? Yes

* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Yesterday Underlords was working fine but today impossible to start, here is the startup command:
https://gist.github.com/colas-sebastien/8e969b109ae4222d2c7db4e183e1dfba

#### Steps for reproducing this issue:

1. Lanch Underlords

**Comment by colas-sebastien** [comment]
Here is my dump file:
[dump.zip](https://github.com/ValveSoftware/Dota-Underlords/files/3559009/dump.zip)

**Comment by colas-sebastien** [comment]
I read all the close issues and I launched my game with:

> ./underlords.sh -vulkan_disable_steam_shader_cache

It is working well

**Comment by sysofd** [comment]
I confirm this problem

**Comment by sysofd** [comment]
Maybe clean shader cache fixed this problem ?

**Comment by sysofd** [comment]
> I read all the close issues and I launched my game with:
> 
> > ./underlords.sh -vulkan_disable_steam_shader_cache
> 
> It is working well

What video driver do you use?
I use nvidia 430.40

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in librendersystemvulkan.so.

**Comment by colas-sebastien** [comment]
How can I clean my shader cache ?
My Nvidia version is: 430.40

**Comment by mbedded** [comment]
I have the same issue. The solution from #1 helped me.

> Can you try running with -vulkan_disable_steam_shader_cache and see if that helps?
> https://github.com/ValveSoftware/Dota-Underlords/issues/1#issuecomment-501878994

**Comment by danginsburg** [comment]
Fix for this will ship in the next update.  Thanks for reporting.

**Comment by colas-sebastien** [comment]
Thanks !!!!
I will test it on the next update

**Comment by pixelr0** [comment]
same here on Ubuntu 16.04 (first time i see this bug)
i had to launch the game with "-vulkan_disable_steam_shader_cache" to make it start

**Comment by pixelr0** [comment]
another thing that i've noticed before failure to start was the increasing startup time, from a couple of seconds at first to almost one minute! so there is something fishy with your shaders Valve!

**Comment by stuartpb** [comment]
A quick way to clear the shader cache for Underlords, as a workaround until the fix is deployed: `rm -r ~/.steam/steam/steamapps/shadercache/1046930`

**Comment by danginsburg** [comment]
Should be fixed now with the latest update.
