### ISSUE TITLE
Freeze when playing games in linux

### ISSUE THREAD

**Issue by hxse** [ValveSoftware/Dota-Underlords#33]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`)  [my system information](https://gist.github.com/hxse/f575e51ddd710ae948c39a4a6e2dcea7): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
When I play the game, it will freeze, the mouse and keyboard will not respond, and even the power button will not respond.
[my dota underlords log](https://gist.github.com/hxse/a06c8f1e8bea9a63b959604e838f4700)

#### Steps for reproducing this issue:
The time of occurrence is random and cannot be reproduced

**Comment by ForeGone-G** [comment]
I am probably late to the party. Got kinda the same problem though.
Here are my [system specs](https://gist.github.com/ForeGone-G/2edb971f29e68974abc21847df324a73).

I got this problem on two games so far:
Wolcen, Version 1.0.1.0: (When a reward window pops up)
We Were Here Together: When entering the second level.

Unfortunately I cannot say if it's the same for me for Dota2, but it seems to be the same issue. When trying to switch out of the game nothing really responds. When I wait a REALLY long time after Alt + Ctrl + T, Yakuake is opening up. I can then kill the process by SIGTERM it through htop. Other than that, there's only pushing the reset button.

The sound of the game will still play when this issue happens. Also in htop, 2-3 of my CPU cores are on 100%, used by the game and Xorg.
