### ISSUE TITLE
Random crashes on Linux

### ISSUE THREAD

**Issue by jlubea** [ValveSoftware/Dota-Underlords#34]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/jlubea/f9deaa9c67f5f510b9afe5fd57e9cbd8
* Have you checked for system updates?: Yes (Ubuntu 19.10)
* Are you using the latest stable video driver available for your system? Yes (ubuntu-driver-440)
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Used to work great. Then the Big Update happened.
2. Used to freeze or crash, now it just crashes... perhaps when moving the mouse or pressing keys on the keyboard?
3. I can get through a game, but I usually have to recover from at least 1 crash each game. The most number of crashes in a game has been 3... start Dota Underlords again and "Reconnect" in game.

The bugs are much better than they were even a few days ago, and the crashes seem to be more infrequent, but they're still occurring.

Latest crash dump:

[dota-underlords-crashes.zip](https://github.com/ValveSoftware/Dota-Underlords/files/3780196/dota-underlords-crashes.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in libclient.so.

**Comment by jlubea** [comment]
I pulled the dump from /tmp/dumps

Is there another location that I should pull a crash dump from?

**Comment by shpinog** [comment]
I have the same problem. Archlinux, the latest drivers. Kernel is from the valve repository and the standard does not matter, it is still random crashes. I tried the amdvlk and mesa-aco drivers, took out the shader cache, anyway random crashes. There was no such problem before a major update.

[crash_20191029115140_1.dmp](url)

**Comment by FrankieEnc** [comment]
same issue, same specs. turning the graphics setting to basic has helped(not more crashing during gameplay) but now the initial load is broken (sometimes the background doesn't load, it's all blue, and sometimes the hud doesn't load so i cannot buy) and every game requires a restart.

**Comment by jlubea** [comment]
Another crash dump...
[dota-underlords-crashes-2.zip](https://github.com/ValveSoftware/Dota-Underlords/files/3790773/dota-underlords-crashes-2.zip)

**Comment by jlubea** [comment]
A day or two ago a normal game update was released. I haven't had a crash for the past 2 days. Thanks to whoever fixed the client!

**Comment by kisak-valve** [comment]
Closing per the last comment.
