### ISSUE TITLE
Game crashes sometimes during battles, Linux, AMD

### ISSUE THREAD

**Issue by stradus64** [ValveSoftware/Dota-Underlords#35]
* System information from steam : https://gist.github.com/nadomodan/a26565023a1cc2b4f2842387f015e633
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

During the battle, at some point, usually during the later rounds the game just stops for few seconds and crashes, I relaunch the game to reconnect, sometimes it will crash again at later round. No known precise way to reproduce, I'm just watching the round's battle, not clicking anything and it suddenly crashes sometimes, usually near the beginning of battle. I've seen Arch and Ubuntu users experience this.

/tmp/dumps: [dumps.zip](https://github.com/ValveSoftware/Dota-Underlords/files/3781334/dumps.zip)

Not mine, some more from another player: https://www.reddit.com/r/underlords/comments/dnpvbe/dota_underlords_update_for_late_102619_102719_hot/f5favis/
`kernel: GlobPool5[7566]: segfault at 1a8 ip 00007fc625b6def0 sp 00007fc63e069ad0 error 4 in libclient.so[7fc625170000+1262000]
 kernel: Code: 49 8b 07 48 8b 80 a8 01 00 00 48 8b 7d b0 f3 0f 10 a8 08 01 00 00 f3 0f 10 88 0c 01 00 00 48 89 f0 66 0f 1f 84 00 00 00 00 00 <49> 8b 91 a8 01 00 00 4c 8d 6
 crash_20191027112949_1.dmp[8066]: Finished uploading minidump (out-of-process): success = yes
 crash_20191027112949_1.dmp[8066]: response: CrashID=bp-88a981eb-ccba-4f39-b11f-207a62191027
 crash_20191027112949_1.dmp[8066]: file ''/tmp/dumps/crash_20191027112949_1.dmp'', upload yes: ''CrashID=bp-88a981eb-ccba-4f39-b11f-207a62191027''
 gnome-shell[2088]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x70000b7
 gnome-shell[2088]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x70000b7
 crash_20191027131132_1.dmp[8147]: Uploading dump (out-of-process)
                                   /tmp/dumps/crash_20191027131132_1.dmp
 kernel: traps: GlobPool3[8090] general protection fault ip:7ff78cd15ef0 sp:7ff7a5313b40 error:0 in libclient.so[7ff78c318000+1262000]
 crash_20191027131132_1.dmp[8147]: Finished uploading minidump (out-of-process): success = yes
 crash_20191027131132_1.dmp[8147]: response: CrashID=bp-c47eefdb-3d45-46f4-a549-37f852191027
 crash_20191027131132_1.dmp[8147]: file ''/tmp/dumps/crash_20191027131132_1.dmp'', upload yes: ''CrashID=bp-c47eefdb-3d45-46f4-a549-37f852191027''
 gnome-shell[2088]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x70000b7
 gnome-shell[2088]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x70000b7
 crash_20191027131249_1.dmp[8244]: Uploading dump (out-of-process)
                                   /tmp/dumps/crash_20191027131249_1.dmp
 kernel: GlobPool6[8205]: segfault at 3f8001a8 ip 00007f1db275def0 sp 00007f1dcabd8ad0 error 4 in libclient.so[7f1db1d60000+1262000]
 kernel: Code: 49 8b 07 48 8b 80 a8 01 00 00 48 8b 7d b0 f3 0f 10 a8 08 01 00 00 f3 0f 10 88 0c 01 00 00 48 89 f0 66 0f 1f 84 00 00 00 00 00 <49> 8b 91 a8 01 00 00 4c 8d 6
 crash_20191027131249_1.dmp[8244]: Finished uploading minidump (out-of-process): success = yes
 crash_20191027131249_1.dmp[8244]: response: CrashID=bp-a2874e30-4030-4bae-8b44-7aba72191027
 crash_20191027131249_1.dmp[8244]: file ''/tmp/dumps/crash_20191027131249_1.dmp'', upload yes: ''CrashID=bp-a2874e30-4030-4bae-8b44-7aba72191027''
`

**Comment by kisak-valve** [comment]
Hello @nadomodan, the backtrace you've provided is the same as #34. Closing in favor of the existing issue report.
