### ISSUE TITLE
Streaming: Game does not start while display device is powered down

### ISSUE THREAD

**Issue by stuartpb** [ValveSoftware/Dota-Underlords#36]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/stuartpb/a2a2eaf9b698af722403b5aee04c095f
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

When attempting to stream Underlords to another system from my desktop computer while my desktop monitor is off, the streaming client presents a normal, moving cursor, but the game does not start, and the stream itself only shows the last screen image that was displayed before the monitor was shut down (eg. the desktop, with the system clock showing the time that I turned it off).

If I turn the monitor back on at any point after the stream has been established, the game does start (displaying the Valve logo splash screen on both the local and remote machines), without any sound. (Sound initializes and streams normally when streaming is started while the display is powered on.)

Other games will also fail to stream when the display device is turned off (tested with Slay the Spire), but those streams fail to initialize altogether (the streaming client displays the tiling loading screen for a few seconds, then exits back to the Steam library).

#### Steps for reproducing this issue:

1. Power down the display device (ie. monitor) on the host that Underlords will be streamed from (ie. a desktop).
2. Stream Underlords from the device with the powered-down display to another client (ie. a notebook).

**Comment by gdrewb-valve** [comment]
This doesn't appear to be an Underlords issue so we need to figure out where this feedback should go to.

When you do this without streaming what happens?  It'll obviously be inconvenient to use the UI without the monitor being on but if you position the mouse on the launch button, turn the monitor off, click the button, wait a while and then turn the monitor back on what do you see?  Did the game make progress starting up while the monitor was off or is it also delayed?  On Slay the Spire does it start up or does it fail to start?

**Comment by gdrewb-valve** [comment]
Closing pending feedback.
