### ISSUE TITLE
Ubuntu 18.04: LoadSYstemAndDependencies(): CAppSystemDict: Unable to load module client (Dependency of application), error 2

### ISSUE THREAD

**Issue by dennis1du** [ValveSoftware/Dota-Underlords#38]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/dennis1du/5a426f0f3feb1c85af0903dfe199b44b): 

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Nothing similar before. One point is that actually I could run the game yesterday. Then I ran the "cleaning download cache" in the end. Now when I launch steam and it says that I need to install Underlords again, and I have been getting stuck into this error till now.

#### Steps for reproducing this issue:

1. Verification doesn't work
2. Cannot launch Underlords
3.

**Comment by kisak-valve** [comment]
Hello @dennis1du, does `/tmp/dumps/<username>_stdout.txt` or `~/.steam/error.log` have any hints?

**Comment by dennis1du** [comment]
> Hello @dennis1du, does `/tmp/dumps/<username>_stdout.txt` or `~/.steam/error.log` have any hints?

Hi @kisak-valve , I am not sure about the location `/tmp/dumps/<username>_stdout.txt` or `~/.steam/error.log`. Kind of new to Linux, sorry about that

**Comment by sbernard31** [comment]
Same problem for me. It seems this is because of missing libva.so.2.
See : https://steamcommunity.com/app/1046930/discussions/0/1638675549008848958/

I'm on debian 9 and there is no package which contain libva.so.2 (only libva.so.1)

**Comment by dennis1du** [comment]
> Same problem for me. It seems this is because of missing libva.so.2.
> See : https://steamcommunity.com/app/1046930/discussions/0/1638675549008848958/
> 
> I'm on debian 9 and there is no package which contain libva.so.2 (only libva.so.1)

Wow, I see. Is there any fix? Thx

**Comment by dennis1du** [comment]
> Same problem for me. It seems this is because of missing libva.so.2.
> See : https://steamcommunity.com/app/1046930/discussions/0/1638675549008848958/
> 
> I'm on debian 9 and there is no package which contain libva.so.2 (only libva.so.1)

Actually, I have neither libva.so.1 nor libva.so.2 in `Underlords/game/bin/linuxstreamrt64`

**Comment by sbernard31** [comment]
I'm not a dev of dotaunderlord, just a user.
In my case maybe upgrading to debian 10 should solve the problem as debian 10 seems to have this package in version 2, but this is a bit overkill !

@dennis1du try `dpkg -l | grep libva` in a terminal you should see the version of the package on your system.

@kisak-valve Is this new dependency expected ?

**Comment by dennis1du** [comment]
> I'm not a dev of dotaunderlord, just a user.
> In my case maybe upgrading to debian 10 should solve the problem as debian 10 seems to have this package in version 2, but this is a bit overkill !
> 
> @dennis1du try `dpkg -l | grep libva` in a terminal you should see the version of the package on your system.
> 
> @kisak-valve Is this new dependency expected ?

Thanks so much! It seems the similar issue in the steam discussion!

**Comment by sbernard31** [comment]
@kisak-valve do not hesitate to ask me for more information (logs or dump).

**Comment by kisak-valve** [comment]
Thanks @sbernard31, `libva.so.2` was [recently added](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1600394952171527192) to Steam's runtime and will make its way into the next stable release of the Steam client.

You can opt into Steam's beta client (Steam -> Settings -> Beta participation) or for most currently supported distro releases with a command similar to `sudo apt install libva2` to resolve this issue.

**Comment by dennis1du** [comment]
> Thanks @sbernard31, `libva.so.2` was [recently added](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1600394952171527192) to Steam's runtime and will make its way into the next stable release of the Steam client.
> 
> You can opt into Steam's beta client (Steam -> Settings -> Beta participation) or for most currently supported distro releases with a command similar to `apt install libva2` to resolve this issue.

Thanks so much. Will try that later.

**Comment by sbernard31** [comment]
@kisak-valve I just tested to use the [beta client](https://www.wikihow.com/Enable-Steam-Beta) and it works for me.

:pray:  thx !

**Comment by dennis1du** [comment]
@kisak-valve The [beta client](https://www.wikihow.com/Enable-Steam-Beta) works very well. Thx so much! Guess this issue can be closed.
