### ISSUE TITLE
Invisible character models on non-native resolutions (desktop-friendly fullscreen)

### ISSUE THREAD

**Issue by Pobega** [ValveSoftware/Dota-Underlords#4]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Pobega/824d9aa4d1bfefb9973417f0e3c970bb
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes (Flatpak Mesa)
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
The character models in the bench are invisible. Character models in the shop are also invisible.

#### Steps for reproducing this issue:

1. Install Steam Flatpak on Intel HD graphics
2. Run Underlords, play a game, verify invisible character models

[Screenshots of the bug hosted on imgur here](https://imgur.com/a/JEHfIkz)

This may be something fixed in Mesa 19, but I have no way to test as there's no Freedesktop SDK with Mesa 19 available at the current time.

Edit: Updated the title. See https://github.com/ValveSoftware/Dota-Underlords/issues/4#issuecomment-502336565 to see that this wasn't the fault of the Steam Flatpak, but rather non-native resolutions.

**Comment by danginsburg** [comment]
I'm not sure there is anything I can do if you can't update mesa, but I would like to figure out what is the minimum mesa version that is running it properly on Intel HD Graphics so we can recommend that to people.

**Comment by danginsburg** [comment]
For what it's worth I had personally tested Skylake with mesa 18.3.3 and it was working fine.

**Comment by Pobega** [comment]
Yep, I'm not expecting a fix but I figure it was worth documenting.

I'm not 100% sure the issue is related to Mesa, that's just a hunch based on something @.kisak-valve mentioned in another issue related to Proton: https://github.com/ValveSoftware/Proton/issues/2476#issuecomment-480257514

I was hoping to just have it confirmed whether the VK_EXT_transform_feedback was being used by Underlords.

I run Fedora Silverblue so I only use Steam via the Flatpak, but I'll return here to update/close this ticket if a future Mesa update fixes the issue.

**Comment by danginsburg** [comment]
Nope, doesn't use VK_EXT_transform_feedback and also doesn't run through DXVK/Proton.  Source 2 is using its own Vulkan renderer directly.

**Comment by danginsburg** [comment]
Oh - wait, are you running the Windows version through Proton instead of the native version?

**Comment by Pobega** [comment]
Right, I know it's native I was just (perhaps naively) assuming that the transform kisak mentioned was being used (since if that transform was missing in Mesa it'd effect both DXVK **and** native Vulkan apps.)

And no, I'm running it native.

**Comment by Pobega** [comment]
If it works on 18.3.3 as you mentioned and I'm seeing this issue on 18.3.6 in the Flatpak the issue may not be related to Mesa at all, then.

Of note is that it works fine on my desktop running Steam Flatpak with Nvidia 418-74

**Comment by Pobega** [comment]
I messed around with the settings a bit more, this seems to be related to running at any non-native resolution. When I went back to 1080p it worked as expected.

Apologies for not testing that first, I'm so used to turning down the resolution on Intel HD graphics I didn't even consider that would be the issue.

**Comment by danginsburg** [comment]
Good lead, thanks.  I'm going to see if I can repro here.
