### ISSUE TITLE
Launch Error - No Video

### ISSUE THREAD

**Issue by JesseDotEXE** [ValveSoftware/Dota-Underlords#43]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/JesseDotEXE/fa89c1d5fb09d0f7858d31cdc7dd1f50
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Log File: 
https://gist.github.com/JesseDotEXE/387cfdf95a09d4545a8d4c43b60ae9ed

System Details: 
Dell XPS 9575 using pop_os 19.10 with a GTX 2060 connected via eGPU and external monitor. There is also an internal discrete GPU the RX Vega M GL. The issue also occurs when using just the laptop and the internal GPU.

Issue: 
Whenever I launch the Underlords game it loads to a screen that looks exactly like my desktop(captures whatever is on the screen at the time). From there, I can hear music but the video never starts for the game it just has a "screenshot" of my desktop.

#### Steps for reproducing this issue:

1. Launch Underlords

**Comment by danginsburg** [comment]
This looks strange, I don't see any of the Vulkan initialization messages at all.  Are you running through Proton/Steam Play perhaps and not the actual native Linux version?

**Comment by JesseDotEXE** [comment]
Shoot, you are right, sorry I did try to use Proton to see if that would resolve the issue.
Here is a new gist after a native reinstall: https://gist.github.com/JesseDotEXE/53e78d4cb5391f6f4e976feadeade97d

**Comment by kisak-valve** [comment]
Hello @JesseDotEXE, it looks like Dota Underlords is trying to render with the AMD chipset. Maybe try adding `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia %command%` to the game's launch options?

Alternatively, you could try to use a newer mesa build with the AMD chipset from a PPA like [oibaf](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) or [kisak-mesa](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa).

**Comment by JesseDotEXE** [comment]
So, I guess this laptop has issues with the integrated graphics card. I'd say its a device issue on my part and we can close this.
