### ISSUE TITLE
Game froze immediately after start and could not be closed (Windows 10)

### ISSUE THREAD

**Issue by chriszo111** [ValveSoftware/Dota-Underlords#45]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/chriszo111/fe7b19393a525e92aae26b355fafec7a#file-steam_system_information
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes `445.87` (GeForce Game Ready Driver)
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

- What _did_ happened
Started the game via Steam and immediately after the game froze and I could only kill it forcibly via CMD
- What I _expected_ should happen
Start the game via Steam and see the Valve trailer in a 100% sized borderless window
- Additional log output from crash
https://gist.github.com/chriszo111/fe7b19393a525e92aae26b355fafec7a#file-console-log-1

#### Steps for reproducing this issue:

1. Launch Dota Underlords by clicking 'Play' within the games Steam library page
2. `underlords.exe` stops reacting
> Whenever I click something with the mouse I get a frozen screen. Switching through apps with `[ALT]+[TAB]` is possible and the windows are also not stuck as long as I use the keyboard only. I assume, since I run Underlords in _Borderless Windowed_ mode, that this window at the launch of the app overlapped all other windows and then froze so that it wasn't minimizable again.
3. Frozen process can only be killed via CMD `Taskkill \IM underlords.exe \F` (has to be forced)
4. Run Dota Underlords again through Steam library
5. Game starts fine

**Comment by kisak-valve** [comment]
Hello @chriszo111, this issue tracker is limited to issues with the Mac and Linux client of Dota Underlords. Please use https://underlords.com/feedback/ for your issue to reach the appropriate developers.

**Comment by chriszo111** [comment]
Just saw this issue tracker is only for Linux and macOS, but the issue seems related to similar freezes on Linux and macOS. Will report to said link as well.

**Comment by chriszo111** [comment]
Same freeze / timeout happens frequently now
https://gist.github.com/chriszo111/fe7b19393a525e92aae26b355fafec7a#file-console-log-18052020

**Comment by chriszo111** [comment]
I just checked `common\Underlords\game\dac\cfg\video.txt` where both `setting.nowindowborder` and `setting.fullscreen` were set to `1`. I set `fullscreen` to `0` and the game started without problems after. The in-game setting was `noborderwindow=1` and my best guess is `fullscreen` should have been `0`, but it wasn't set properly when updating the setting in-game.
