### ISSUE TITLE
Dota Underlords crash on linux

### ISSUE THREAD

**Issue by FHenry** [ValveSoftware/Dota-Underlords#47]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
[systemsettings.txt](https://github.com/ValveSoftware/Dota-Underlords/files/7367502/systemsettings.txt)

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes  470.74
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
On 2 laptops, both on Ubuntu 20.04.3 with 470.74 nvidia driver. I put here only one log file, but the error is the same on both (Error creating shader  and Error loading resource file)

#### Steps for reproducing this issue:

1. Run Dota Underlords

The screen flickering like it will start and no, return to desktop

[console.log](https://github.com/ValveSoftware/Dota-Underlords/files/7367497/console.log)

**Comment by ghost** [comment]
i have the same issue on arch
[crash_20211022131713_2.txt](https://github.com/ValveSoftware/Dota-Underlords/files/7396123/crash_20211022131713_2.txt)
[steamlog.txt](https://github.com/ValveSoftware/Dota-Underlords/files/7396125/steamlog.txt)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in librendersystemvulkan.so.

**Comment by ghost** [comment]
is there any workaround?

**Comment by BloodyIron** [comment]
I'm on 470.86 and crashing immediately...

running through proton seems to work, but like cmon VALVe

**Comment by ghost** [comment]
> I'm on 470.86 and crashing immediately...
> 
> running through proton seems to work, but like cmon VALVe

Can you play online using proton?

**Comment by BloodyIron** [comment]
> > I'm on 470.86 and crashing immediately...
> > running through proton seems to work, but like cmon VALVe
> 
> Can you play online using proton?

Actually no it has issues connecting to steam servers, yet... shows my profile??? so weird...

**Comment by PTsuarez** [comment]
Having the same issue, immediate crash on the native version and the inability to play while running it through proton. Works fine on windows and android though. 

There doesn't seem to be a fix that I can find and steam support referred me here... so I guess it's just bot games from now on.

**Comment by jecs** [comment]
I upgraded my drivers to 470 and am now having the same issue. The game won't launch with vulkan. Proton lacks online play. opengl gives me a blank screen.

**Comment by FHenry** [comment]
Same symptoms with Nvidia 495.46

**Comment by jecs** [comment]
Upgrading to driver 510 seems to have fixed all issues, not just in Dota Underlords but also in Dota 2. See a related issue [here](https://github.com/ValveSoftware/Dota-2-Vulkan/issues/393). Driver 510 came out recently in the PPAs.

**Comment by PTsuarez** [comment]
> fixed all issues, not just in Dota Underlords

Can you log in properly and play online?

**Comment by jecs** [comment]
> > fixed all issues, not just in Dota Underlords
> 
> Can you log in properly and play online?

Yes.
