### ISSUE TITLE
Any hope for OpenGL?

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-Underlords#5]
Hi.

While on my old PC with Linux Dota 2 works quite well (still). Unfortunately, I can not run Dota Underlords because it requires the Vulkan API.

Unfortunately, my old Radeon HD 5850 card does not support Vulkan.

Do you have any plans for adding OpenGL support?

**Comment by danginsburg** [comment]
Sorry, currently we require Vulkan and at the moment are not planning to support OpenGL.

**Comment by AngryPenguinPL** [comment]
> Sorry, currently we require Vulkan and at the moment are not planning to support OpenGL.

Thanks for reply.

Can you tell me one more thing, is the Windows version also Vulkan only or is it working on DirectX 9/10/11?

I'm asking because I'm wondering if it can be run via SteamPlay in Proton?

**Comment by danginsburg** [comment]
Windows version is DX11.

**Comment by AngryPenguinPL** [comment]
Thanks :)
