### ISSUE TITLE
No quit button in mobile UI

### ISSUE THREAD

**Issue by Jayman2000** [ValveSoftware/Dota-Underlords#7]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Jayman2000/1313137164208281a9d9ecaaa044aa6d
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

I enabled the mobile interface mode. I expected for there to be a quit button on the game's title screen. There is no quit button when the mobile interface is enabled. The game did not produce any command line output (I check by setting the launch options to "%command% &> log").

#### Steps for reproducing this issue:

1. From the title screen, click the gear, go to the "game" tab, and set "interface mode" to "Mobile".
2. Return to the main menu.

**Comment by danginsburg** [comment]
This tracker is for Linux/macOS-specific issues, although I'll pass this along.
