### ISSUE TITLE
No game display only sounds 

### ISSUE THREAD

**Issue by nisabuan** [ValveSoftware/Dota-Underlords#8]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/nisabuan/79f85687bf1dc7b64391a1f5052c4b72): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
no game display only sounds (video link = http://srecorder.com/s/7h1i)

#### Steps for reproducing this issue:

1. Update driver
2. Check others game, and no some problem in others game
![Screenshot_17](https://user-images.githubusercontent.com/19486949/59574502-a57d3b80-90e1-11e9-913d-e485ccd7ef34.png)

**Comment by kisak-valve** [comment]
Hello @nisabuan, this issue tracker is limited to issues with the Mac and Linux port of Dota Underlords.

Please use https://www.valvesoftware.com/en/contact?recipient=Dota+Underlords+Team for issues with the game on Windows.
