### ISSUE TITLE
Vulcan not Supported, Any chance for a Battlepass refund?

### ISSUE THREAD

**Issue by elotrocoso** [ValveSoftware/Dota-Underlords#9]
I know this is not the right place for asking this, but I honestly do not know where else to ask. I have no interest in dota and only bought the battle pass to play underlords early, unfortunately I had no access to the information regarding the incompatibility with my GPU. Is there any chance to get a refund. Also, will the open beta be accessible on mobile?
Sorry for the bother!

**Comment by kisak-valve** [comment]
Hello @elotrocoso, what video card / driver version are you using? Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Account issues including refunds are not handled on this issue tracker. Please use [Steam Support](https://help.steampowered.com/en/) for that.

**Comment by elotrocoso** [comment]
Hi Kisak, Im using a AMD Radeon HD 6490M, driver ver. 1.2, here is the GIST:
https://gist.github.com/elotrocoso/abe5f03c94b6a6f8165f19700b31df04

**Comment by kisak-valve** [comment]
The AMD Radeon HD 6490M is a Terascale 2 architecture chipset. There are no video drivers that support Vulkan (or Metal with macOS) on this hardware generation.
